name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.6', '3.7', '3.8', '3.9']
    name: Testing krait with python ${{ matrix.python }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Ensure latest pip
        run: pip install --upgrade pip

      - name: Install dependencies and script
        run: pip install -r requirements.txt -r test-requirements.txt -e .

      - name: Lint with flake8
        run: flake8
      - name: Run static type analyzer
        run: mypy

      - name: Test with pytest
        run: pytest tests/

      - name: Create new krait click project
        run: krait --skip-config create -n '' -e '' -s project

      - name: Install & test newly created project
        run: |
          cd project
          pip install -e .[tests]
          project --help
          pytest

      - name: Clean up new project
        run: cd .. & rm -rf project

      - name: Create new krait lib project
        run: krait create -n '' -e '' -p library -s project

      - name: Install & test newly created project
        run: |
          cd project
          pip install -e .[tests]
          pytest

      - name: Clean up new project
        run: cd .. & rm -rf project
